---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "wallabag.fullname" . }}
  labels:
    {{- include "wallabag.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "wallabag.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "wallabag.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: wallabag
          image: {{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.targetPort }}
          env:
          {{- range $key, $value := .Values.env }}
          - name: {{ $key }}
            value: "{{ $value }}"
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- if .Values.securityContext }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: wallabag-data
              mountPath: /var/www/wallabag/data
            - name: wallabag-var
              mountPath: /var/www/wallabag/var
            - name: tmp
              mountPath: /tmp
      {{- if .Values.podSecurityContext }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- end }}
      volumes:
        - name: tmp
          emptyDir:
            medium: Memory
            sizeLimit: 500Mi
        - name: wallabag-var
          emptyDir:
            sizeLimit: 5Gi
        - name: wallabag-data
          hostPath:
            path: {{ .Values.persistence.hostPath }}
            type: Directory
