apiVersion: apps/v1
kind: Deployment
metadata:
  name: wallabag
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wallabag
  template:
    metadata:
      labels:
        app: wallabag
    spec:
      containers:
        - name: wallabag
          image: "wallabag/wallabag:2.5.2"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          env:
            - name: SYMFONY__ENV__DOMAIN_NAME
              value: "{{ .Values.env.DOMAIN_NAME }}"
          volumeMounts:
            - name: wallabag-data
              mountPath: /var/www/wallabag/data
      volumes:
        - name: wallabag-data
          hostPath:
            path: {{ .Values.persistence.hostPath }}
            type: Directory
