{{ if .Values.ingress.enabled }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "wallabag.fullname" . }}
  labels:
    {{- include "wallabag.labels" . | nindent 4 }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/affinity: cookie
    nginx.ingress.kubernetes.io/proxy-connect-timeout: {{ .Values.ingress.proxyConnectTimeout }}
    nginx.ingress.kubernetes.io/proxy-read-timeout: {{ .Values.ingress.proxyReadTimeout }}
    {{- if .Values.issuer.enabled }}
    cert-manager.io/issuer: {{ include "wallabag.fullname" . }}
    {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
  - host: {{ .Values.ingress.domainName }}
    http:
      paths:
      - backend:
          service:
            name: {{ include "wallabag.fullname" . }}
            port:
              number: {{ .Values.service.port }}
        path: /
        pathType: ImplementationSpecific
{{ if .Values.ingress.tls.enabled }}
  tls:
  - hosts:
    - {{ .Values.ingress.domainName }}
    secretName: {{ include "wallabag.fullname" . }}-tls-secret
{{- end }}
{{- end }}
